version: "3.8"
services:
  mongo:
    container_name: mongo-macbooksg
    image: ${MONGO_DB_IMAGE}
    environment:
      - MONGODB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGO_DB_USERNAME}
      - MONGODB_PASSWORD=${MONGO_DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - ./database/db:/bitnami/mongodb